# Generated by Django 3.1.7 on 2021-04-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_item',
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(related_name='tags', to='posts.Post'),
        ),
    ]
