# Generated by Django 3.1.7 on 2021-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210424_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_avatar',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
