# Generated by Django 3.1.7 on 2021-06-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_post_preview_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
