# Generated by Django 3.1.7 on 2021-09-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20210913_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='tags', to='posts.Tag'),
        ),
    ]
