# Generated by Django 3.1.7 on 2021-09-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20210913_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, related_name='tags', to='posts.Tag'),
        ),
    ]
