# Generated by Django 3.1.7 on 2021-09-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20210914_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, default='', related_name='tags', to='posts.Tag'),
        ),
    ]
