# Generated by Django 3.1.7 on 2021-05-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210501_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org_level',
        ),
    ]
