# Generated by Django 3.1.7 on 2021-05-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
    ]
