# Generated by Django 3.1.7 on 2021-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210810_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='https://twitter.com/'),
        ),
    ]
