# Generated by Django 3.1.7 on 2021-08-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210810_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vk_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='https://facebook/public/'),
        ),
    ]
