# Generated by Django 3.1.7 on 2021-08-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210810_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_1',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
