# Generated by Django 3.1.7 on 2021-08-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_role_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_1',
            new_name='role',
        ),
    ]
