# Generated by Django 3.1.7 on 2021-05-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210530_1239'),
        ('polls', '0002_poll_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
