# Generated by Django 3.1.7 on 2021-05-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210530_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='post',
        ),
    ]
