# Generated by Django 3.1.7 on 2021-08-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20210814_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Deadline',
            field=models.CharField(choices=[('Full_Time_Key', 'Full Time'), ('Part_Time_Key', 'Part Time'), ('Freelance_Key', 'Freelance')], max_length=300),
        ),
    ]
