# Generated by Django 3.1.7 on 2021-08-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_auto_20210814_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Deadline',
            field=models.CharField(choices=[('full', 'Full Time'), ('part', 'Part Time'), ('freelance', 'Freelance')], max_length=300),
        ),
    ]
