# Generated by Django 3.1.7 on 2021-08-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_auto_20210814_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='Deadline',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='Position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='Salary',
            new_name='salary',
        ),
    ]
