# Generated by Django 3.1.7 on 2021-08-18 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_auto_20210818_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='choices',
        ),
        migrations.AddField(
            model_name='group',
            name='choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
